# Generated by Django 3.2.4 on 2021-07-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='data_posted',
            new_name='date_posted',
        ),
    ]
