#!/bin/bash

mysql -u root --password="$MYSQL_ROOT_PASSWORD"  << EOF
USE ${MYSQL_DATABASE};
CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_USER}';
GRANT ALL PRIVILEGES ON  *.* TO '${MYSQL_USER}';
FLUSH PRIVILEGES;
EOF